# -*- coding: utf-8 -*-
"""One-shot seed for authentic Azkar and Dua JSON assets."""
import json
from pathlib import Path

from dua_i18n import localized_title, localized_translation

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "assets" / "json"
OUT.mkdir(parents=True, exist_ok=True)

AZKAR = [
    "سُبْحَانَ اللَّهِ",
    "الْحَمْدُ لِلَّهِ",
    "اللَّهُ أَكْبَرُ",
    "لَا إِلَهَ إِلَّا اللَّهُ",
    "لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ",
    "أَسْتَغْفِرُ اللَّهَ",
    "أَسْتَغْفِرُ اللَّهَ وَأَتُوبُ إِلَيْهِ",
    "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ",
    "سُبْحَانَ اللَّهِ الْعَظِيمِ",
    "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ، سُبْحَانَ اللَّهِ الْعَظِيمِ",
    "لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ",
    "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    "أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ",
    "رَبِّ اغْفِرْ لِي",
    "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ",
    "حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ",
    "حَسْبِيَ اللَّهُ لَا إِلَهَ إِلَّا هُوَ، عَلَيْهِ تَوَكَّلْتُ، وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ",
    "رَضِيتُ بِاللَّهِ رَبًّا، وَبِالْإِسْلَامِ دِينًا، وَبِمُحَمَّدٍ ﷺ نَبِيًّا",
    "اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ",
    "اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ",
    "أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ",
    "أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ",
    "اللَّهُمَّ بِكَ أَصْبَحْنَا، وَبِكَ أَمْسَيْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ النُّشُورُ",
    "اللَّهُمَّ بِكَ أَمْسَيْنَا، وَبِكَ أَصْبَحْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ الْمَصِيرُ",
    "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ",
    "بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ، وَهُوَ السَّمِيعُ الْعَلِيمُ",
    "اللَّهُمَّ عَافِنِي فِي بَدَنِي، اللَّهُمَّ عَافِنِي فِي سَمْعِي، اللَّهُمَّ عَافِنِي فِي بَصَرِي",
    "يَا حَيُّ يَا قَيُّومُ، بِرَحْمَتِكَ أَسْتَغِيثُ",
    "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَافِيَةَ فِي الدُّنْيَا وَالْآخِرَةِ",
    "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ",
    "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْعَجْزِ وَالْكَسَلِ",
    "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْجُبْنِ وَالْبُخْلِ",
    "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ غَلَبَةِ الدَّيْنِ وَقَهْرِ الرِّجَالِ",
    "رَبِّ اشْرَحْ لِي صَدْرِي وَيَسِّرْ لِي أَمْرِي",
    "رَبِّ زِدْنِي عِلْمًا",
    "رَبَّنَا لَا تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا",
    "رَبَّنَا اغْفِرْ لِي وَلِوَالِدَيَّ وَلِلْمُؤْمِنِينَ",
    "اللَّهُمَّ اغْفِرْ لِي، وَارْحَمْنِي، وَاهْدِنِي، وَعَافِنِي، وَارْزُقْنِي",
    "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْهُدَى وَالتُّقَى وَالْعَفَافَ وَالْغِنَى",
    "اللَّهُمَّ آتِ نَفْسِي تَقْوَاهَا، وَزَكِّهَا أَنْتَ خَيْرُ مَنْ زَكَّاهَا",
    "اللَّهُمَّ إِنِّي ظَلَمْتُ نَفْسِي ظُلْمًا كَثِيرًا، وَلَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ",
    "سُبْحَانَ اللَّهِ، وَالْحَمْدُ لِلَّهِ، وَلَا إِلَهَ إِلَّا اللَّهُ، وَاللَّهُ أَكْبَرُ",
    "لَا إِلَهَ إِلَّا أَنْتَ سُبْحَانَكَ إِنِّي كُنْتُ مِنَ الظَّالِمِينَ",
    "اللَّهُمَّ أَعِنِّي عَلَى ذِكْرِكَ وَشُكْرِكَ وَحُسْنِ عِبَادَتِكَ",
    "جَزَى اللَّهُ عَنَّا مُحَمَّدًا ﷺ مَا هُوَ أَهْلُهُ",
    "اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا، وَرِزْقًا طَيِّبًا، وَعَمَلًا مُتَقَبَّلًا",
    "رَبِّ أَوْزِعْنِي أَنْ أَشْكُرَ نِعْمَتَكَ الَّتِي أَنْعَمْتَ عَلَيَّ",
    "اللَّهُمَّ بَارِكْ لِي فِيمَا أَعْطَيْتَ",
    "اللَّهُمَّ قِنِي عَذَابَكَ يَوْمَ تَبْعَثُ عِبَادَكَ",
    "آمَنْتُ بِاللَّهِ وَرُسُلِهِ",
    "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ أَنْ أُشْرِكَ بِكَ وَأَنَا أَعْلَمُ",
    "اللَّهُمَّ اجْعَلْنِي مِنَ التَّوَّابِينَ، وَاجْعَلْنِي مِنَ الْمُتَطَهِّرِينَ",
    "سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ، أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا أَنْتَ",
    "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ عَذَابِ الْقَبْرِ",
    "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ فِتْنَةِ الْمَحْيَا وَالْمَمَاتِ",
    "اللَّهُمَّ أَنْتَ السَّلَامُ وَمِنْكَ السَّلَامُ، تَبَارَكْتَ يَا ذَا الْجَلَالِ وَالْإِكْرَامِ",
    "اللَّهُمَّ لَا سَهْلَ إِلَّا مَا جَعَلْتَهُ سَهْلًا، وَأَنْتَ تَجْعَلُ الْحَزْنَ إِذَا شِئْتَ سَهْلًا",
]

DUAS = [
    ("eating-start", "Khana khane se pehle ki dua", "بِسْمِ اللَّهِ", "In the name of Allah."),
    ("eating-forget", "Khana shuru karte waqt Bismillah bhoolne ki dua", "بِسْمِ اللَّهِ أَوَّلَهُ وَآخِرَهُ", "In the name of Allah at its beginning and at its end."),
    ("eating-end", "Khana khane ke baad ki dua", "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنِي هَذَا وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ", "Praise be to Allah Who fed me this and provided it for me, with no power or might from myself."),
    ("drinking", "Peene ki dua", "بِسْمِ اللَّهِ", "In the name of Allah."),
    ("milk", "Doodh peene ki dua", "اللَّهُمَّ بَارِكْ لَنَا فِيهِ وَزِدْنَا مِنْهُ", "O Allah, bless it for us and give us more of it."),
    ("waking", "Neend se uthne ki dua", "الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ", "Praise be to Allah Who gave us life after He caused us to die, and to Him is the resurrection."),
    ("sleeping", "Sone ki dua", "بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا", "In Your name, O Allah, I die and I live."),
    ("sleeping-long", "Sone se pehle lambi dua", "اللَّهُمَّ بِاسْمِكَ أَمُوتُ وَأَحْيَا", "O Allah, in Your name I die and I live."),
    ("toilet-enter", "Toilet mein daakhil hone ki dua", "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْخُبُثِ وَالْخَبَائِثِ", "O Allah, I seek refuge in You from the male and female unclean spirits."),
    ("toilet-exit", "Toilet se nikalne ki dua", "غُفْرَانَكَ", "I seek Your forgiveness."),
    ("wudu-start", "Wazu shuru karne ki dua", "بِسْمِ اللَّهِ", "In the name of Allah."),
    ("wudu-end", "Wazu ke baad ki dua", "أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ", "I bear witness that there is no god but Allah, alone without partner, and that Muhammad is His servant and Messenger."),
    ("home-enter", "Ghar mein daakhil hone ki dua", "بِسْمِ اللَّهِ وَلَجْنَا، وَبِسْمِ اللَّهِ خَرَجْنَا، وَعَلَى اللَّهِ رَبِّنَا تَوَكَّلْنَا", "In the name of Allah we enter, in the name of Allah we leave, and upon Allah our Lord we place our trust."),
    ("home-exit", "Ghar se nikalne ki dua", "بِسْمِ اللَّهِ، تَوَكَّلْتُ عَلَى اللَّهِ، وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ", "In the name of Allah, I place my trust in Allah, and there is no power and no strength except with Allah."),
    ("masjid-enter", "Masjid mein daakhil hone ki dua", "اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ", "O Allah, open for me the gates of Your mercy."),
    ("masjid-exit", "Masjid se nikalne ki dua", "اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ", "O Allah, I ask You from Your bounty."),
    ("travel", "Safar ki dua", "سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ، وَإِنَّا إِلَى رَبِّنَا لَمُنْقَلِبُونَ", "Glory be to Him Who has subjected this to us, and we could not have it by our efforts. Indeed, to our Lord we will return."),
    ("travel-return", "Safar se wapas aane ki dua", "آيِبُونَ تَائِبُونَ عَابِدُونَ لِرَبِّنَا حَامِدُونَ", "We return, repenting, worshipping, and praising our Lord."),
    ("rain", "Barish ki dua", "اللَّهُمَّ صَيِّبًا نَافِعًا", "O Allah, make it a beneficial downpour."),
    ("thunder", "Bijli aur baadal ki dua", "سُبْحَانَ الَّذِي يُسَبِّحُ الرَّعْدُ بِحَمْدِهِ وَالْمَلَائِكَةُ مِنْ خِيفَتِهِ", "Glory be to Him Whom thunder glorifies with His praise, and the angels from fear of Him."),
    ("wind", "Hawa chalne ki dua", "اللَّهُمَّ إِنِّي أَسْأَلُكَ خَيْرَهَا، وَخَيْرَ مَا فِيهَا، وَخَيْرَ مَا أُرْسِلَتْ بِهِ", "O Allah, I ask You for its good, the good within it, and the good it was sent with."),
    ("new-clothes", "Naye kapre pehanne ki dua", "اللَّهُمَّ لَكَ الْحَمْدُ أَنْتَ كَسَوْتَنِيهِ، أَسْأَلُكَ مِنْ خَيْرِهِ وَخَيْرِ مَا صُنِعَ لَهُ", "O Allah, praise is Yours; You have clothed me with it. I ask You for its good and the good for which it was made."),
    ("mirror", "Aaina dekhne ki dua", "اللَّهُمَّ كَمَا حَسَّنْتَ خَلْقِي فَحَسِّنْ خُلُقِي", "O Allah, as You have made my appearance beautiful, make my character beautiful."),
    ("anger", "Gusse ki dua", "أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ", "I seek refuge in Allah from Satan, the accursed."),
    ("calamity", "Museebat ki dua", "إِنَّا لِلَّهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ، اللَّهُمَّ أْجُرْنِي فِي مُصِيبَتِي وَأَخْلِفْ لِي خَيْرًا مِنْهَا", "Indeed we belong to Allah and to Him we will return. O Allah, reward me in my calamity and replace it with something better."),
    ("anxiety", "Pareshani aur gham ki dua", "لَا إِلَهَ إِلَّا أَنْتَ سُبْحَانَكَ إِنِّي كُنْتُ مِنَ الظَّالِمِينَ", "There is no god but You; glory be to You. Indeed I was among the wrongdoers."),
    ("debt", "Qarz se nijat ki dua", "اللَّهُمَّ اكْفِنِي بِحَلَالِكَ عَنْ حَرَامِكَ، وَأَغْنِنِي بِفَضْلِكَ عَمَّنْ سِوَاكَ", "O Allah, suffice me with what You have made lawful so that I have no need of what You have made unlawful, and make me independent of all others besides You."),
    ("rizq", "Rizq ki dua", "اللَّهُمَّ إِنِّي أَسْأَلُكَ رِزْقًا طَيِّبًا، وَعِلْمًا نَافِعًا، وَعَمَلًا مُتَقَبَّلًا", "O Allah, I ask You for lawful provision, beneficial knowledge, and accepted deeds."),
    ("knowledge", "Ilm ki dua", "رَبِّ زِدْنِي عِلْمًا", "My Lord, increase me in knowledge."),
    ("parents", "Walidain ke liye dua", "رَبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا", "My Lord, have mercy on them as they raised me when I was small."),
    ("children", "Aulad ke liye dua", "رَبِّ هَبْ لِي مِنْ لَدُنْكَ ذُرِّيَّةً طَيِّبَةً إِنَّكَ سَمِيعُ الدُّعَاءِ", "My Lord, grant me from Yourself good offspring. Indeed, You are the Hearer of supplication."),
    ("spouse", "Ghar wale ke liye dua", "رَبَّنَا هَبْ لَنَا مِنْ أَزْوَاجِنَا وَذُرِّيَّاتِنَا قُرَّةَ أَعْيُنٍ", "Our Lord, grant us from our spouses and offspring comfort to our eyes."),
    ("guest", "Mehman nawazi ki dua", "اللَّهُمَّ بَارِكْ لَهُمْ فِيمَا رَزَقْتَهُمْ، وَاغْفِرْ لَهُمْ، وَارْحَمْهُمْ", "O Allah, bless them in what You have provided them, forgive them, and have mercy on them."),
    ("sneezing", "Chheenkne wale ki dua", "الْحَمْدُ لِلَّهِ", "Praise be to Allah."),
    ("sneezing-reply", "Chheenkne wale ko jawab", "يَرْحَمُكَ اللَّهُ", "May Allah have mercy on you."),
    ("sneezing-reply2", "Chheenk ke jawab ka jawab", "يَهْدِيكُمُ اللَّهُ وَيُصْلِحُ بَالَكُمْ", "May Allah guide you and set your affairs right."),
    ("visiting-sick", "Bimar ki iyadat ki dua", "لَا بَأْسَ، طَهُورٌ إِنْ شَاءَ اللَّهُ", "No harm, it is a purification, if Allah wills."),
    ("for-sick", "Bimar ke liye shifa ki dua", "اللَّهُمَّ رَبَّ النَّاسِ، أَذْهِبِ الْبَأْسَ، اشْفِهِ وَأَنْتَ الشَّافِي", "O Allah, Lord of mankind, remove the harm, heal him, for You are the Healer."),
    ("after-adhan", "Azan ke baad ki dua", "اللَّهُمَّ رَبَّ هَذِهِ الدَّعْوَةِ التَّامَّةِ، وَالصَّلَاةِ الْقَائِمَةِ، آتِ مُحَمَّدًا الْوَسِيلَةَ وَالْفَضِيلَةَ", "O Allah, Lord of this perfect call and the prayer about to be performed, grant Muhammad the Wasila and virtue."),
    ("iqamah", "Iqamat ke baad", "أَقَامَهَا اللَّهُ وَأَدَامَهَا", "May Allah establish it and make it perpetual."),
    ("iftitah", "Namaz shuru karne ki dua", "سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ، وَتَبَارَكَ اسْمُكَ، وَتَعَالَى جَدُّكَ، وَلَا إِلَهَ غَيْرُكَ", "Glory and praise be to You, O Allah. Blessed is Your name, exalted is Your majesty, and there is no god besides You."),
    ("ruku", "Ruku ki tasbih", "سُبْحَانَ رَبِّيَ الْعَظِيمِ", "Glory be to my Lord, the Magnificent."),
    ("sujud", "Sajde ki tasbih", "سُبْحَانَ رَبِّيَ الْأَعْلَى", "Glory be to my Lord, the Most High."),
    ("tashahhud", "Tashahhud", "التَّحِيَّاتُ لِلَّهِ وَالصَّلَوَاتُ وَالطَّيِّبَاتُ", "All compliments, prayers, and pure words are for Allah."),
    ("salawat", "Durood Ibrahimi", "اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ، كَمَا صَلَّيْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ", "O Allah, send blessings upon Muhammad and the family of Muhammad, as You sent blessings upon Ibrahim and the family of Ibrahim."),
    ("qunoot", "Dua-e-Qunoot", "اللَّهُمَّ اهْدِنِي فِيمَنْ هَدَيْتَ، وَعَافِنِي فِيمَنْ عَافَيْتَ", "O Allah, guide me among those You have guided, and grant me well-being among those You have granted well-being."),
    ("after-salam", "Namaz ke baad ki dua", "أَسْتَغْفِرُ اللَّهَ، أَسْتَغْفِرُ اللَّهَ، أَسْتَغْفِرُ اللَّهَ", "I seek forgiveness from Allah (three times)."),
    ("salam-after", "Namaz ke baad salam wali dua", "اللَّهُمَّ أَنْتَ السَّلَامُ وَمِنْكَ السَّلَامُ، تَبَارَكْتَ يَا ذَا الْجَلَالِ وَالْإِكْرَامِ", "O Allah, You are Peace and from You is peace. Blessed are You, O Owner of majesty and honor."),
    ("laylatul-qadr", "Shab-e-Qadr ki dua", "اللَّهُمَّ إِنَّكَ عَفُوٌّ تُحِبُّ الْعَفْوَ فَاعْفُ عَنِّي", "O Allah, You are Pardoning and love to pardon, so pardon me."),
    ("ramadan-iftar", "Iftar ki dua", "ذَهَبَ الظَّمَأُ، وَابْتَلَّتِ الْعُرُوقُ، وَثَبَتَ الْأَجْرُ إِنْ شَاءَ اللَّهُ", "The thirst is gone, the veins are moistened, and the reward is confirmed, if Allah wills."),
    ("suhoor", "Sehri ki niyat", "وَبِصَوْمِ غَدٍ نَوَيْتُ مِنْ شَهْرِ رَمَضَانَ", "I intend to fast tomorrow in the month of Ramadan."),
    ("breaking-fast-guest", "Iftar karwane wale ke liye dua", "أَفْطَرَ عِنْدَكُمُ الصَّائِمُونَ، وَأَكَلَ طَعَامَكُمُ الْأَبْرَارُ، وَصَلَّتْ عَلَيْكُمُ الْمَلَائِكَةُ", "May the fasting people break their fast with you, may the righteous eat your food, and may the angels send blessings upon you."),
    ("istikhara", "Istikhara ki dua", "اللَّهُمَّ إِنِّي أَسْتَخِيرُكَ بِعِلْمِكَ، وَأَسْتَقْدِرُكَ بِقُدْرَتِكَ، وَأَسْأَلُكَ مِنْ فَضْلِكَ الْعَظِيمِ", "O Allah, I seek the good from You by Your knowledge, I seek ability from You by Your power, and I ask You from Your immense bounty."),
    ("protection", "Hifazat ki dua", "بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ", "In the name of Allah, with Whose name nothing on earth or in heaven can cause harm, and He is the All-Hearing, All-Knowing."),
    ("evil-eye", "Nazar-e-bad se hifazat", "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّةِ مِنْ كُلِّ شَيْطَانٍ وَهَامَّةٍ، وَمِنْ كُلِّ عَيْنٍ لَامَّةٍ", "I seek refuge in the perfect words of Allah from every devil and poisonous creature, and from every evil eye."),
    ("whisper", "Waswase ki dua", "أَعُوذُ بِاللَّهِ السَّمِيعِ الْعَلِيمِ مِنَ الشَّيْطَانِ الرَّجِيمِ", "I seek refuge in Allah, the All-Hearing, All-Knowing, from Satan the accursed."),
    ("market", "Bazaar ki dua", "لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، يُحْيِي وَيُمِيتُ، وَهُوَ حَيٌّ لَا يَمُوتُ، بِيَدِهِ الْخَيْرُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ", "There is no god but Allah, alone without partner. His is the dominion and His is the praise. He gives life and causes death, and He is Ever-Living and does not die. In His hand is all good, and He is over all things competent."),
    ("new-year", "Naye saal / naye kaam ki dua", "اللَّهُمَّ بَارِكْ لَنَا فِي رَجَبَ وَشَعْبَانَ، وَبَلِّغْنَا رَمَضَانَ", "O Allah, bless us in Rajab and Sha'ban, and let us reach Ramadan."),
    ("friday", "Jummah ki dua", "اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ", "O Allah, send blessings upon Muhammad and upon the family of Muhammad."),
    ("entering-gathering", "Majlis mein baithne ki dua", "رَبِّ اغْفِرْ لِي وَتُبْ عَلَيَّ، إِنَّكَ أَنْتَ التَّوَّابُ الرَّحِيمُ", "My Lord, forgive me and accept my repentance. Indeed You are the Accepting of repentance, the Merciful."),
    ("leaving-gathering", "Majlis se uthne ki kaffara dua", "سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ، أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا أَنْتَ، أَسْتَغْفِرُكَ وَأَتُوبُ إِلَيْكَ", "Glory and praise be to You, O Allah. I bear witness that there is no god but You. I seek Your forgiveness and repent to You."),
    ("seeing-afflicted", "Museebat zada dekhne ki dua", "الْحَمْدُ لِلَّهِ الَّذِي عَافَانِي مِمَّا ابْتَلَاكَ بِهِ، وَفَضَّلَنِي عَلَى كَثِيرٍ مِمَّنْ خَلَقَ تَفْضِيلًا", "Praise be to Allah Who spared me from what He has tested you with, and Who favored me greatly over many of those He created."),
    ("hearing-rooster", "Murgh ki awaz par dua", "اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ", "O Allah, I ask You of Your bounty."),
    ("hearing-donkey", "Gadhe ki awaz par dua", "أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ", "I seek refuge in Allah from Satan, the accursed."),
    ("new-moon", "Chand dekhne ki dua", "اللَّهُمَّ أَهِلَّهُ عَلَيْنَا بِالْيُمْنِ وَالْإِيمَانِ، وَالسَّلَامَةِ وَالْإِسْلَامِ", "O Allah, bring it over us with blessing and faith, safety and Islam."),
    ("after-rain", "Barish ke baad ki dua", "مُطِرْنَا بِفَضْلِ اللَّهِ وَرَحْمَتِهِ", "We have been given rain by the bounty and mercy of Allah."),
    ("distress", "Sakht pareshani ki dua", "لَا إِلَهَ إِلَّا اللَّهُ الْعَظِيمُ الْحَلِيمُ، لَا إِلَهَ إِلَّا اللَّهُ رَبُّ الْعَرْشِ الْعَظِيمِ", "There is no god but Allah, the Magnificent, the Forbearing. There is no god but Allah, Lord of the Mighty Throne."),
    ("guidance", "Hidayat ki dua", "رَبَّنَا لَا تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا وَهَبْ لَنَا مِنْ لَدُنْكَ رَحْمَةً", "Our Lord, do not let our hearts deviate after You have guided us, and grant us mercy from Yourself."),
    ("forgiveness", "Maghfirat ki dua", "رَبِّ اغْفِرْ لِي وَتُبْ عَلَيَّ إِنَّكَ أَنْتَ التَّوَّابُ الرَّحِيمُ", "My Lord, forgive me and accept my repentance. Indeed You are the Accepting of repentance, the Merciful."),
    ("jannah", "Jannat ki dua", "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ", "Our Lord, give us good in this world and good in the Hereafter, and protect us from the punishment of the Fire."),
    ("death", "Husn-e-khatima ki dua", "اللَّهُمَّ أَحْيِنِي مَا كَانَتِ الْحَيَاةُ خَيْرًا لِي، وَتَوَفَّنِي إِذَا كَانَتِ الْوَفَاةُ خَيْرًا لِي", "O Allah, keep me alive as long as life is better for me, and take me when death is better for me."),
    ("grave", "Qabr ke azaab se hifazat", "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ عَذَابِ الْقَبْرِ", "O Allah, I seek refuge in You from the punishment of the grave."),
    ("dajjal", "Dajjal ki fitne se hifazat", "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ فِتْنَةِ الْمَسِيحِ الدَّجَّالِ", "O Allah, I seek refuge in You from the trial of the False Messiah."),
    ("morning", "Subah ki dua", "اللَّهُمَّ بِكَ أَصْبَحْنَا، وَبِكَ أَمْسَيْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ النُّشُورُ", "O Allah, by You we enter the morning, by You we enter the evening, by You we live, by You we die, and to You is the resurrection."),
    ("evening", "Shaam ki dua", "اللَّهُمَّ بِكَ أَمْسَيْنَا، وَبِكَ أَصْبَحْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ الْمَصِيرُ", "O Allah, by You we enter the evening, by You we enter the morning, by You we live, by You we die, and to You is the return."),
    ("ayatul-kursi-intent", "Ayat-ul-Kursi ke baad hifazat", "اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ", "Allah — there is no god except Him, the Ever-Living, the Sustainer of existence."),
    ("last-two-surahs", "Mu'awwidhatain parhne ki niyat", "قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ", "Say: I seek refuge in the Lord of daybreak."),
    ("ikhlas", "Surah Ikhlas ki fazilat", "قُلْ هُوَ اللَّهُ أَحَدٌ", "Say: He is Allah, the One."),
    ("istiadha", "Shaitan se panah", "أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ", "I seek refuge in Allah from Satan, the accursed."),
    ("basmala", "Kaam shuru karne ki dua", "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ", "In the name of Allah, the Entirely Merciful, the Especially Merciful."),
    ("thanking-someone", "Shukriya ada karne ki dua", "جَزَاكَ اللَّهُ خَيْرًا", "May Allah reward you with good."),
    ("reply-thank", "JazakAllah ka jawab", "وَإِيَّاكَ، بَارَكَ اللَّهُ فِيكَ", "And you; may Allah bless you."),
    ("wedding", "Nikah ki mubarakbad", "بَارَكَ اللَّهُ لَكَ، وَبَارَكَ عَلَيْكَ، وَجَمَعَ بَيْنَكُمَا فِي خَيْرٍ", "May Allah bless you, send blessings upon you, and join you both in goodness."),
    ("newborn", "Naye bache ke liye dua", "أُعِيذُهُ بِكَلِمَاتِ اللَّهِ التَّامَّةِ مِنْ كُلِّ شَيْطَانٍ وَهَامَّةٍ وَمِنْ كُلِّ عَيْنٍ لَامَّةٍ", "I seek protection for him in the perfect words of Allah from every devil, poisonous creature, and evil eye."),
    ("aqiqah-intent", "Aqiqah ki dua", "اللَّهُمَّ هَذَا مِنْكَ وَلَكَ", "O Allah, this is from You and for You."),
    ("janazah", "Mayyit ke liye dua", "اللَّهُمَّ اغْفِرْ لَهُ وَارْحَمْهُ، وَعَافِهِ وَاعْفُ عَنْهُ", "O Allah, forgive him and have mercy on him, grant him well-being and pardon him."),
    ("visiting-grave", "Qabristan ki ziyarat ki dua", "السَّلَامُ عَلَيْكُمْ أَهْلَ الدِّيَارِ مِنَ الْمُؤْمِنِينَ وَالْمُسْلِمِينَ، وَإِنَّا إِنْ شَاءَ اللَّهُ بِكُمْ لَلَاحِقُونَ", "Peace be upon you, O people of the dwellings, believers and Muslims. Indeed we, if Allah wills, will join you."),
    ("after-wudu-extra", "Wazu ke baad jannat ki dua", "اللَّهُمَّ اجْعَلْنِي مِنَ التَّوَّابِينَ، وَاجْعَلْنِي مِنَ الْمُتَطَهِّرِينَ", "O Allah, make me among those who repent and make me among those who purify themselves."),
    ("before-wudu-niyyah", "Wazu ki niyat", "نَوَيْتُ الْوُضُوءَ لِرَفْعِ الْحَدَثِ لِلَّهِ تَعَالَى", "I intend ablution to lift impurity, for the sake of Allah the Exalted."),
    ("leaving-home-long", "Ghar se nikalte waqt hifazat", "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ أَنْ أَضِلَّ أَوْ أُضَلَّ، أَوْ أَزِلَّ أَوْ أُزَلَّ، أَوْ أَظْلِمَ أَوْ أُظْلَمَ، أَوْ أَجْهَلَ أَوْ يُجْهَلَ عَلَيَّ", "O Allah, I seek refuge in You from going astray or being led astray, from slipping or being caused to slip, from wronging or being wronged, from acting ignorantly or being treated ignorantly."),
    ("mounting", "Sawari par chadhne ki dua", "بِسْمِ اللَّهِ، الْحَمْدُ لِلَّهِ، سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا", "In the name of Allah, praise be to Allah. Glory be to Him Who subjected this to us."),
    ("on-return-home", "Safar se ghar aane ki dua", "تَوْبًا تَوْبًا لِرَبِّنَا أَوْبًا، لَا يُغَادِرُ عَلَيْنَا حَوْبًا", "Repenting, returning to our Lord, leaving no sin upon us."),
    ("seeing-something-pleasing", "Kuch achha dekhne ki dua", "الْحَمْدُ لِلَّهِ الَّذِي بِنِعْمَتِهِ تَتِمُّ الصَّالِحَاتُ", "Praise be to Allah, by Whose blessing good things are completed."),
    ("seeing-something-displeasing", "Kuch bura dekhne ki dua", "الْحَمْدُ لِلَّهِ عَلَى كُلِّ حَالٍ", "Praise be to Allah in every circumstance."),
    ("wearing-ihram", "Ihram ki talbiyah", "لَبَّيْكَ اللَّهُمَّ لَبَّيْكَ، لَبَّيْكَ لَا شَرِيكَ لَكَ لَبَّيْكَ", "Here I am, O Allah, here I am. Here I am, You have no partner, here I am."),
    ("tawaf", "Tawaf ke dauran", "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ", "Our Lord, give us good in this world and good in the Hereafter, and protect us from the Fire."),
    ("safa-marwa", "Safa Marwah ki dua", "إِنَّ الصَّفَا وَالْمَرْوَةَ مِنْ شَعَائِرِ اللَّهِ", "Indeed, Safa and Marwah are among the symbols of Allah."),
    ("arrafat", "Arafat ki dua", "لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ", "There is no god but Allah, alone without partner. His is the dominion and His is the praise, and He is over all things competent."),
    ("after-sadaqah", "Sadqah dene ke baad", "اللَّهُمَّ تَقَبَّلْ مِنَّا إِنَّكَ أَنْتَ السَّمِيعُ الْعَلِيمُ", "O Allah, accept from us. Indeed You are the All-Hearing, All-Knowing."),
    ("before-study", "Parhai shuru karne ki dua", "رَبِّ اشْرَحْ لِي صَدْرِي وَيَسِّرْ لِي أَمْرِي وَاحْلُلْ عُقْدَةً مِنْ لِسَانِي", "My Lord, expand my chest for me, make my task easy, and untie the knot from my tongue."),
    ("after-study", "Parhai ke baad ki dua", "اللَّهُمَّ انْفَعْنِي بِمَا عَلَّمْتَنِي، وَعَلِّمْنِي مَا يَنْفَعُنِي", "O Allah, benefit me by what You have taught me, and teach me what will benefit me."),
    ("ease", "Mushkil aasan karne ki dua", "اللَّهُمَّ لَا سَهْلَ إِلَّا مَا جَعَلْتَهُ سَهْلًا، وَأَنْتَ تَجْعَلُ الْحَزْنَ إِذَا شِئْتَ سَهْلًا", "O Allah, there is no ease except what You make easy, and You make the difficult easy if You will."),
    ("taqwa", "Taqwa ki dua", "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْهُدَى وَالتُّقَى وَالْعَفَافَ وَالْغِنَى", "O Allah, I ask You for guidance, piety, chastity, and self-sufficiency."),
    ("good-character", "Achhe akhlaq ki dua", "اللَّهُمَّ كَمَا أَحْسَنْتَ خَلْقِي فَأَحْسِنْ خُلُقِي", "O Allah, as You have made my form good, make my character good."),
    ("sincerity", "Ikhlas ki dua", "اللَّهُمَّ اجْعَلْ عَمَلِي كُلَّهُ صَالِحًا، وَاجْعَلْهُ لِوَجْهِكَ خَالِصًا", "O Allah, make all my deeds righteous and make them sincerely for Your sake."),
    ("ummah", "Ummah ke liye dua", "اللَّهُمَّ أَصْلِحْ أُمَّةَ مُحَمَّدٍ", "O Allah, rectify the Ummah of Muhammad."),
    ("palestine", "Mazloomon ke liye dua", "اللَّهُمَّ كُنْ لِلْمُسْتَضْعَفِينَ نَاصِرًا", "O Allah, be a helper for the oppressed."),
    ("rain-stop", "Zyada barish rukwane ki dua", "اللَّهُمَّ حَوَالَيْنَا وَلَا عَلَيْنَا", "O Allah, around us and not upon us."),
    ("entering-market-short", "Dukaan / market ki mukhtasar dua", "لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ", "There is no god but Allah, alone, without partner."),
    ("after-eating-short", "Khana ke baad mukhtasar shukr", "الْحَمْدُ لِلَّهِ", "Praise be to Allah."),
    ("when-in-pain", "Dard ki dua", "أَعُوذُ بِاللَّهِ وَقُدْرَتِهِ مِنْ شَرِّ مَا أَجِدُ وَأُحَاذِرُ", "I seek refuge in Allah and His power from the evil of what I feel and fear."),
    ("before-sleep-ayat", "Sone se pehle Ayat-ul-Kursi", "اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ", "Allah — there is no god except Him, the Ever-Living, the Sustainer. Neither drowsiness nor sleep overtakes Him."),
    ("on-waking-night", "Raat ko uthne ki dua", "لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ", "There is no god but Allah, alone without partner. His is the dominion and His is the praise, and He is over all things competent."),
    ("istighfar-sayyid", "Sayyid-ul-Istighfar", "اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ", "O Allah, You are my Lord; there is no god but You. You created me and I am Your servant, and I am upon Your covenant and promise as much as I am able."),
    ("for-deceased-child", "Naye marhoom ke liye dua", "اللَّهُمَّ اجْعَلْهُ فَرَطًا وَذُخْرًا لِوَالِدَيْهِ", "O Allah, make him a forerunner and a treasure for his parents."),
    ("after-salam-33", "Namaz ke baad 33 tasbih ki niyat", "سُبْحَانَ اللَّهِ، الْحَمْدُ لِلَّهِ، اللَّهُ أَكْبَرُ", "Glory be to Allah, praise be to Allah, Allah is the Greatest."),
    ("entering-bathroom-long", "Hammam / toilet ki lambi dua", "بِسْمِ اللَّهِ، اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْخُبُثِ وَالْخَبَائِثِ", "In the name of Allah. O Allah, I seek refuge in You from the male and female unclean spirits."),
    ("on-hearing-good-news", "Khushkhabri par dua", "الْحَمْدُ لِلَّهِ الَّذِي بِنِعْمَتِهِ تَتِمُّ الصَّالِحَاتُ", "Praise be to Allah, by Whose blessing righteous affairs are completed."),
    ("when-given-gift", "Tohfa milne par dua", "بَارَكَ اللَّهُ لَكَ فِي أَهْلِكَ وَمَالِكَ", "May Allah bless you in your family and your wealth."),
    ("before-meal-host", "Mehman ke ghar khana khane ki dua", "اللَّهُمَّ أَطْعِمْ مَنْ أَطْعَمَنِي، وَاسْقِ مَنْ سَقَانِي", "O Allah, feed the one who has fed me, and give drink to the one who has given me drink."),
]

assert len(AZKAR) >= 50, len(AZKAR)
assert len(DUAS) >= 100, len(DUAS)
assert len({d[0] for d in DUAS}) == len(DUAS)

if __name__ == "__main__":
    (OUT / "azkar.json").write_text(
        json.dumps([{"arabic": a} for a in AZKAR], ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    (OUT / "duas.json").write_text(
        json.dumps(
            [
                {
                    "id": i,
                    "arabic_text": ar,
                    "title": localized_title(i, t),
                    "translation": localized_translation(i, tr),
                }
                for i, t, ar, tr in DUAS
            ],
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )
    print(f"Wrote {len(AZKAR)} azkar and {len(DUAS)} duas")
